# Generated by Django 2.2 on 2019-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('available', models.BooleanField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
